- name: Install dnf-automatic
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Replace automatic.conf
  ansible.builtin.copy:
    src: dnf/automatic.conf
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '644'

- name: Enable dnf-automatic.timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: yes
    state: started