- name: Include ssl_bot group vars
  ansible.builtin.include_vars:
    file: ../../group_vars/ssl_bot.yml

- name: Install bind
  ansible.builtin.dnf:
    name: bind
    state: present

- name: Manage named.conf
  ansible.builtin.template:
    src: named.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: "640"
  register: named_config

- name: Manage TSIG keys for slaves
  ansible.builtin.template:
    src: tsig.j2
    dest: /etc/named/{{ item }}.key
    owner: root
    group: named
    mode: "640"
  loop: "{{ dns_slaves }}"

- name: Manage TSIG keys for ssl bots
  ansible.builtin.template:
    src: tsig.j2
    dest: /etc/named/{{ acme_tsig_prefix }}.{{ item }}.key
    owner: root
    group: named
    mode: "640"
  vars:
    is_ssl_bot_loop: true
  loop: "{{ acme_hosts.keys() }}"

- name: Manage zone configurations
  ansible.builtin.template:
    src: zone_config.j2
    dest: /etc/named/{{ item }}.conf
    owner: root
    group: named
    mode: "640"
  loop: "{{ dns_zones }}"
  register: zone_config

- name: Manage zone files
  ansible.builtin.template:
    src: zone/{{ item }}.j2
    dest: /var/named/{{ item }}.zone
    owner: named
    group: named
    mode: "640"
    force: "{% if item == acme_zone %}no{% else %}yes{% endif %}" # We don't want to overwrite a dynamic zone
  loop: "{{ dns_zones }}"
  register: zone_files

- name: Start named service
  ansible.builtin.systemd:
    name: named.service
    state: started
    enabled: yes

- name: restart named
  ansible.builtin.systemd:
    name: named.service
    state: restarted
  when: named_config.changed or zone_config.changed

- name: rndc reload
  ansible.builtin.command: rndc reload
  when: zone_files.changed