- name: Include ssl_bot group vars
  ansible.builtin.include_vars:
    file: ../../group_vars/ssl_bot.yml

- name: Install bind
  ansible.builtin.dnf:
    name: bind
    state: present

- name: Manage named.conf
  ansible.builtin.template:
    src: named.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: "640"
  register: named_config

- name: Manage TSIG keys for slaves
  ansible.builtin.template:
    src: tsig.j2
    dest: /etc/named/{{ item }}.key
    owner: root
    group: named
    mode: "640"
  loop: "{{ dns_slaves.keys() }}"

- name: Manage TSIG keys for ssl bots
  ansible.builtin.template:
    src: tsig.j2
    dest: /etc/named/_acme-challenge.{{ item }}.key
    owner: root
    group: named
    mode: "640"
  vars:
    is_ssl_bot_loop: true
  loop: "{{ acme_hosts.keys() }}"

- name: Manage TSIG keys for workstations
  ansible.builtin.template:
    src: tsig.j2
    dest: /etc/named/_workstation.{{ item }}.key
    owner: root
    group: named
    mode: "640"
  vars:
    is_workstation_loop: true
  loop: "{{ dns_workstations }}"

- name: Manage zone configurations
  ansible.builtin.template:
    src: zone_config.j2
    dest: /etc/named/{{ item }}.conf
    owner: root
    group: named
    mode: "640"
  loop: "{{ dns_zones }}"
  register: zone_config

- name: Manage zone files
  ansible.builtin.template:
    src: zone_base.j2
    dest: /var/named/{{ item }}.zone
    owner: named
    group: named
    mode: "640"
    force: no
  loop: "{{ dns_zones }}"
  register: zone_files

- name: Start named service
  ansible.builtin.systemd:
    name: named.service
    state: started
    enabled: yes

- name: Restart named
  ansible.builtin.systemd:
    name: named.service
    state: restarted
  when: named_config.changed or zone_config.changed

- name: Reload rndc
  ansible.builtin.command: rndc reload
  when: zone_files.changed

- name: Restrict Certificate Authority of all domains to letsencrypt.org
  community.general.nsupdate:
    key_algorithm: "{{ lookup('community.general.passwordstore', 'dns/_workstation.' + hostvars['localhost'].ansible_fqdn + '_tsig_algorithm returnall=yes') }}"
    key_name: "{{ lookup('community.general.passwordstore', 'dns/_workstation.' + hostvars['localhost'].ansible_fqdn + '_tsig_name returnall=yes') }}"
    key_secret: "{{ lookup('community.general.passwordstore', 'dns/_workstation.' + hostvars['localhost'].ansible_fqdn + '_tsig_secret returnall=yes') }}"
    record: "{{ item }}."
    server: "{{ dns_master['private_ipv4_address'] }}"
    type: CAA
    value: 0 issue "letsencrypt.org"
    zone: "{{ item }}"
  loop: "{{ dns_zones }}"
  delegate_to: localhost
  become: false
