- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Grant nginx access to SSL key
  ansible.posix.acl:
    path: /etc/pki/tls/private/{{ ansible_fqdn }}.key.pem
    entity: nginx
    etype: user
    permissions: r
    state: present

- name: Manage nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "644"
  register: nginx_config

- name: Manage /etc/nginx/conf.d
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nginx/conf.d/{{ item | basename | regex_replace('\.j2', '') }}
    owner: root
    group: root
    mode: "644"
  with_fileglob:
    - ../templates/conf.d/*
  register: nginx_conf_d

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx.service
    state: started
    enabled: yes

- name: Restart nginx service
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted
  when: nginx_config.changed or nginx_conf_d.changed
